# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
